name: Unity Build

on:
  push:
    branches: ["main"]

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  unity:
    name: Unity build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - iOS
          - Android
          - StandaloneWindows
          - WebGL
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # TODO: We currently have two cache steps.
      # I need to do more research to sort out the correct path forward with both Unity lib caching and git-lfs caching 

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

      - name: Git LFS Pull
        run: git lfs pull

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v2
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          androidAppBundle: true
          allowDirtyBuild: true
          # TODO: We need allowDirtyBuild because of our git-lfs asset hash. Maybe commit that?

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  apple:
    name: Build for Xcode
    needs: unity
    runs-on: macos-latest
    steps:
      # We don't need the 'real' project (hence no LFS)
      # but we need the Gemfile, Fastfile, etc
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: Build-iOS

      - run: ls

      - name: List files
        working-directory: iOS
        run: ls
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true 
      
      - name: Build iOS
        shell: bash
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
          sudo chmod 755 iOS/MapFileParser.sh
          sudo chmod 755 iOS/process_symbols.sh 
          bundle exec fastlane build
          
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}

          # TODO: Read these from Unity project
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
          APP_NAME: ${{ secrets.APP_NAME }}
          BUILD_NUMBER: ${{ github.run_number }}
          VERSION: ${{ secrets.VERSION }}

          # Generate a new .p8 from https://appstoreconnect.apple.com/access/users, then "Keys"
          # I'm trying "App Manager" access
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }} # Raw .p8 value